language: c

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - zlib1g-dev
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - zlib1g-dev
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
    - os: osx
      osx_image: xcode10.1
      addons:
        homebrew:
          update: true
          packages:
            - zlib
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
    - os: osx
      osx_image: xcode10.1
      addons:
        homebrew:
          update: true
          packages:
            - zlib
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..

script:
  - sudo make all install
  - ctest